runtime: nodejs14

entrypoint: yarn prod-VPC

env_variables:
  SQL_PASSWORD: $SQL_PASSWORD
  SQL_HOST: $SQL_HOST
  SQL_USER: $SQL_USER
  SQL_DB: $SQL_DB
  AUTH0_DOMAIN : $AUTH0_DOMAIN
  AUTH0_AUDIENCE : $AUTH0_AUDIENCE
  AUTH0_FRONTEND_CLIENTID: $AUTH0_FRONTEND_CLIENTID
  AUTH0_ADMIN_USERNAME: $AUTH0_ADMIN_USERNAME
  AUTH0_ADMIN_PWD: $AUTH0_ADMIN_PWD
  AUTH0_MGT_TOKEN_TESTING: $AUTH0_MGT_TOKEN_TESTING
  AUTH0_BACKEND_CLIENTID: $AUTH0_BACKEND_CLIENTID
  AUTH0_CLIENT_SECRET_PDTN: $AUTH0_CLIENT_SECRET_PDTN
  CLOUDSTORAGE_SECRET_PASSPHRASE: $CLOUDSTORAGE_SECRET_PASSPHRASE
  ZILLIQA_PRIVATE_KEY: $ZILLIQA_PRIVATE_KEY
  SC2_STARTUP_PRIVATE_KEY: $SC2_STARTUP_PRIVATE_KEY

vpc_access_connector:
  name: projects/equitize-backend/locations/asia-southeast2/connectors/cloudsql-connector