name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  # decrypt:
    # name: Decrypt cloudStorage secret file
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Decrypt cloudstroage secret file
    #     run: ./.github/scripts/decrypt_cloudstorage_secret.sh
    #     env:
    #       CLOUDSTORAGE_SECRET_PASSPHRASE: ${{ secrets.CLOUDSTORAGE_SECRET_PASSPHRASE }}
    #   # This command is just an example to show your secret being printed
    #   # Ensure you remove any print statements of your secrets. GitHub does
    #   # not hide secrets that use this workaround.
    #   - name: Test printing your secret (Remove this step in production)
    #     run: cat ./cloudStorage/keys.json

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Decrypt cloudstroage secret file
        uses: actions/checkout@v2
        run: ./.github/scripts/decrypt_cloudstorage_secret.sh
        env:
          CLOUDSTORAGE_SECRET_PASSPHRASE: ${{ secrets.CLOUDSTORAGE_SECRET_PASSPHRASE }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat ./cloudStorage/keys.json

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Replacing env variables
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_DB: ${{ secrets.SQL_DB }}
          AUTH0_DOMAIN : ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE : ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_FRONTEND_CLIENTID: ${{ secrets.AUTH0_FRONTEND_CLIENTID }}
          AUTH0_ADMIN_USERNAME: ${{ secrets.AUTH0_ADMIN_USERNAME }}
          AUTH0_ADMIN_PWD: ${{ secrets.AUTH0_ADMIN_PWD }}
          AUTH0_MGT_TOKEN_TESTING: ${{ secrets.AUTH0_MGT_TOKEN_TESTING }}
          AUTH0_BACKEND_CLIENTID: ${{ secrets.AUTH0_BACKEND_CLIENTID }}
          AUTH0_CLIENT_SECRET_PDTN: ${{ secrets.AUTH0_CLIENT_SECRET_PDTN }}
          CLOUDSTORAGE_SECRET_PASSPHRASE: ${{ secrets.CLOUDSTORAGE_SECRET_PASSPHRASE }}
          ZILLIQA_PRIVATE_KEY: ${{ secrets.ZILLIQA_PRIVATE_KEY }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}


      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}